### ISSUE TITLE
Example command doesn't work as expected

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/sketch-to-swiftUI#3]
When using this library as in the example given by the `help` command, the library produces an error related to the "extract" command:

`help`:
```
sketch-to-swiftUI|master ⇒ npm start help

> sketch-to-swiftui@0.9.0 start /Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI
> node index.js "help"

index.js <command>

Commands:
  index.js extract  Extracts the provided sketch file into swiftUI

Options:
  --version     Show version number                                    [boolean]
  -o, --output  Folder to output the swift code and assets.[default: "./output"]
  -h, --help    Show help                                              [boolean]

Examples:
  extract -o ./output mysketchfile.sketch  Export the contents of
                                           mysketchfile.sketch into the output
                                           folder
```

Running the example then:

```
sketch-to-swiftUI|master⚡ ⇒ npm start extract -o ./output test.sketch        

> sketch-to-swiftui@0.9.0 start /Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI
> node index.js "extract" "./output" "test.sketch"

fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'extract'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at Function.fromFile (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/sketch-constructor/models/Sketch/Sketch.js:29:31)
    at extract (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/index.js:23:12)
    at Object.<anonymous> (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/index.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'extract'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sketch-to-swiftui@0.9.0 start: `node index.js "extract" "./output" "test.sketch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sketch-to-swiftui@0.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kerrmarin/.npm/_logs/2020-04-06T09_59_20_340Z-debug.log
```

`test.sketch` is a sketch file that exists in that folder.

**Comment by atomoil** [comment]
fixed in #6
