### ISSUE TITLE
Support node15/npm7

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/sketch-to-swiftUI#33]
When running on node15 the conversion fails:
```
    🎨 Processed 77 Layer Styles!

    📝 Processed 79 Text Styles!

Failed to extract TypeError: Cannot read property 'createElementNS' of undefined
    at Object.create (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/paper/dist/paper-full.js:14283:23)
    at Project.exportSVG (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/paper/dist/paper-full.js:14747:26)
    at Object.<anonymous> (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:139:41)
    at step (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:33:23)
    at Object.next (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:14:53)
    at fulfilled (/Users/kerrmarin/dev/01-LVMH/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:5:58)
```

**Comment by kerrmarin-lvmh** [comment]
Fixed in #56
