### ISSUE TITLE
Failure extracting SwiftUI from Sketch file

### ISSUE THREAD

**Issue by kerrmarin** [design-ops/sketch-to-swiftUI#5]
When running this library against a simple sketch file there is an error:

```
Failed to extract TypeError: Cannot read property 'createElementNS' of undefined
```

Full output:

```
sketch-to-swiftUI|master⚡ ⇒ npm start test.sketch 

> sketch-to-swiftui@0.9.0 start /path/sketch-to-swiftUI
> node index.js "test.sketch"

    🎨 Processed 5 Layer Styles!

ERROR: Avenir Next Regular is in a font collection (/System/Library/Fonts/Avenir Next.ttc), but could not be extracted
  (Note, you need to install fonttools - 'brew install fonttools' should do it)
ERROR: Avenir Next Regular is in a font collection (/System/Library/Fonts/Avenir Next.ttc), but could not be extracted
/bin/sh: ttx: command not found
      ⚠️  WARNING: Could not find font 'Some-Font
    📝 Processed 10 Text Styles!

Failed to extract TypeError: Cannot read property 'createElementNS' of undefined
    at Object.create (/path/sketch-to-swiftUI/node_modules/paper/dist/paper-full.js:14283:23)
    at Project.exportSVG (/path/sketch-to-swiftUI/node_modules/paper/dist/paper-full.js:14747:26)
    at Object.<anonymous> (/path/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:139:41)
    at step (/path/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:33:23)
    at Object.next (/path/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:14:53)
    at fulfilled (/path/sketch-to-swiftUI/node_modules/sketch-to-svg/dist/index.js:5:58)
```

appears to be in the `sketch-to-svg` module

**Comment by kerrmarin** [comment]
It appears to be something to do with the assets, both layer and text styles are extracted

**Comment by kerrmarin** [comment]
I've ran the export of the same file that's giving this error in sketch-to-svg and it extracts the assets successfully. It appears it's something to do with how we're using this library... perhaps? Or how it's installed? Maybe because sketch-to-svg is written in typescript?

**Comment by kerrmarin** [comment]
Looks like including jsdom in our dependencies fixes this (I've tested locally). What I don't understand is why it isn't just picked up from sketch-to-svg...


https://github.com/paperjs/paper.js/issues/634#issuecomment-551018788
